# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/auth/code?email=95224294@qq.com
Accept: application/json

###

POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "95224294@qq.com",
  "username": "niuxibo",
  "password": "123456",
  "confirm_password": "123456",
  "code": "1976"
}

###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "95224294@qq.com",
  "password": "123456"
}

###
POST http://127.0.0.1:8000/name/get_name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzIiwic3ViIjoiMSJ9.Bn-bQDN5K2m1q6Vmoc1wZ2nmEpuethXRDJ_iS7QyLuo

{
  "category": "企业名",
  "surname": "",
  "gender": "不限",
  "length": "五字",
  "other": "是一个关于环保新材料的初创公司额",
  "exclude": []
}

###
POST http://127.0.0.1:8000/knowledge/upload
Content-Type: multipart/form-data;boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzIiwic3ViIjoiMSJ9.Bn-bQDN5K2m1q6Vmoc1wZ2nmEpuethXRDJ_iS7QyLuo

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="company_rules.txt"
Content-Type: text/plain

< ./company_rules.txt
--WebAppBoundary--

###
POST http://127.0.0.1:8000/name/generate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzIiwic3ViIjoiMSJ9.Bn-bQDN5K2m1q6Vmoc1wZ2nmEpuethXRDJ_iS7QyLuo

{
  "category": "企业名",
  "surname": "",
  "gender": "不限",
  "length": "五字",
  "other": "是一个关于ai的互联网公司",
  "exclude": []
}

###
POST http://127.0.0.1:8000/name/feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzIiwic3ViIjoiMSJ9.Bn-bQDN5K2m1q6Vmoc1wZ2nmEpuethXRDJ_iS7QyLuo

{
  "thread_id": "cd22e67a-72ff-4cab-8605-3b706de981d0",
  "category": "企业名",
  "feedback": "我喜欢上一轮生成的‘熠新’这个名字。请保留它，并以此为基调，把其他4个名字的第一个字全部换成五行属‘火’的字。"
}

###
POST http://127.0.0.1:8000/name/feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzIiwic3ViIjoiMSJ9.Bn-bQDN5K2m1q6Vmoc1wZ2nmEpuethXRDJ_iS7QyLuo

{
  "thread_id": "cd22e67a-72ff-4cab-8605-3b706de981d0",
  "category": "企业名",
  "feedback": "这次请把除了‘熠新’之外的4个名字，第二个字全部换成表示‘科技感’的字。"
}
